// Generated by CoffeeScript 1.6.3
(function() {
  var Drawer, XbmcClient, about, addEventListener, buttons, click, connect, drawer, form, ip, playIcon, playPause, port, settings, xbmc, xbmcs;

  Drawer = require('drawer');

  XbmcClient = require('xbmc-client');

  buttons = {
    'Player': ['PlayPause', 'Stop'],
    'Input': ['Up', 'Down', 'Left', 'Right', 'Select', 'Back', 'Home']
  };

  ip = document.getElementById('ip');

  port = document.getElementById('port');

  form = ip.parentNode;

  drawer = new Drawer(document.getElementById('drawer'), 'horizontal');

  settings = document.getElementById('settings');

  about = document.getElementById('about');

  xbmcs = document.querySelectorAll('[data-xbmc]');

  playIcon = document.getElementById('PlayPause').children[0];

  xbmc = null;

  playPause = function(iconName) {
    return function() {
      return playIcon.className = 'icon-' + iconName;
    };
  };

  connect = function(ip, port) {
    if (ip !== null && port !== null) {
      xbmc = new XbmcClient(ip, port);
      xbmc.on('play', playPause('pause'));
      xbmc.on('pause', playPause('play'));
      xbmc.on('stop', playPause('play'));
      return xbmc.on('connected', drawer.close());
    }
  };

  if (localStorage.ip !== void 0 && localStorage.port !== void 0) {
    ip.value = localStorage.ip;
    port.value = localStorage.port;
    connect(localStorage.ip, localStorage.port);
  } else {
    drawer.drawTop();
  }

  click = function(elem, cb) {
    elem.addEventListener('click', cb);
    return elem.addEventListener('touchstart', cb);
  };

  addEventListener = function() {
    var addClick, el, method, _i, _len, _results;
    form.addEventListener('submit', function(ev) {
      ev.preventDefault();
      localStorage.ip = ip.value;
      localStorage.port = port.value;
      connect(ip.value, port.value);
      return false;
    });
    click(about, function(e) {
      if (typeof MozActivity !== "undefined" && MozActivity !== null) {
        e.preventDefault();
        new MozActivity({
          name: "view",
          data: {
            type: "url",
            url: "https://marketplace.firefox.com/app/xbmc-simple-remote"
          }
        });
        return false;
      }
      return true;
    });
    click(settings, function(e) {
      return drawer.toggleTop();
    });
    addClick = function(el, method) {
      return click(el, function(e) {
        e.preventDefault();
        e.stopPropagation();
        if (xbmc != null) {
          return xbmc[method]();
        } else {
          return alert('Please specify IP and port of your XBMC.');
        }
      });
    };
    _results = [];
    for (_i = 0, _len = xbmcs.length; _i < _len; _i++) {
      el = xbmcs[_i];
      method = el.getAttribute('data-xbmc');
      _results.push(addClick(el, method));
    }
    return _results;
  };

  addEventListener();

}).call(this);
